"""MCP bridge event constants."""

from typing import Final

MCP_CLIENT_CONNECTING: Final[str] = "mcp.client.connecting"
MCP_CLIENT_CONNECTED: Final[str] = "mcp.client.connected"
MCP_CLIENT_DISCONNECTED: Final[str] = "mcp.client.disconnected"
MCP_CLIENT_RECONNECTING: Final[str] = "mcp.client.reconnecting"
MCP_CLIENT_CONNECTION_FAILED: Final[str] = "mcp.client.connection_failed"
MCP_DISCOVERY_START: Final[str] = "mcp.discovery.start"
MCP_DISCOVERY_COMPLETE: Final[str] = "mcp.discovery.complete"
MCP_DISCOVERY_FAILED: Final[str] = "mcp.discovery.failed"
MCP_DISCOVERY_FILTERED: Final[str] = "mcp.discovery.filtered"
MCP_INVOKE_START: Final[str] = "mcp.invoke.start"
MCP_INVOKE_SUCCESS: Final[str] = "mcp.invoke.success"
MCP_INVOKE_FAILED: Final[str] = "mcp.invoke.failed"
MCP_INVOKE_TIMEOUT: Final[str] = "mcp.invoke.timeout"
MCP_RESULT_MAPPED: Final[str] = "mcp.result.mapped"
MCP_RESULT_UNKNOWN_BLOCK: Final[str] = "mcp.result.unknown_block"
MCP_FACTORY_REUSE_REJECTED: Final[str] = "mcp.factory.reuse_rejected"
MCP_RESULT_ATTACHMENT: Final[str] = "mcp.result.attachment"
MCP_CACHE_HIT: Final[str] = "mcp.cache.hit"
MCP_CACHE_MISS: Final[str] = "mcp.cache.miss"
MCP_CACHE_EVICT: Final[str] = "mcp.cache.evict"
MCP_CONFIG_VALIDATION_FAILED: Final[str] = "mcp.config.validation_failed"
MCP_CLIENT_DISCONNECT_FAILED: Final[str] = "mcp.client.disconnect_failed"
MCP_FACTORY_START: Final[str] = "mcp.factory.start"
MCP_FACTORY_COMPLETE: Final[str] = "mcp.factory.complete"
MCP_FACTORY_SERVER_SKIPPED: Final[str] = "mcp.factory.server_skipped"
MCP_CACHE_STORE_FAILED: Final[str] = "mcp.cache.store_failed"
MCP_FACTORY_CLEANUP: Final[str] = "mcp.factory.cleanup"

# Server-side MCP events (synthorg-api server).
MCP_REGISTRY_REGISTERED: Final[str] = "mcp.registry.registered"
MCP_REGISTRY_DUPLICATE: Final[str] = "mcp.registry.duplicate"
MCP_REGISTRY_FROZEN: Final[str] = "mcp.registry.frozen"
MCP_SCOPING_FILTERED: Final[str] = "mcp.scoping.filtered"
MCP_SERVER_INVOKE_START: Final[str] = "mcp.server.invoke_start"
MCP_SERVER_INVOKE_SUCCESS: Final[str] = "mcp.server.invoke_success"
MCP_SERVER_INVOKE_FAILED: Final[str] = "mcp.server.invoke_failed"
MCP_HANDLER_NOT_IMPLEMENTED: Final[str] = "mcp.handler.not_implemented"
MCP_REGISTRY_BUILT: Final[str] = "mcp.registry.built"
MCP_HANDLERS_BUILT: Final[str] = "mcp.handlers.built"
MCP_TOOL_BUILDER_INVALID_REQUIRED: Final[str] = "mcp.tool_builder.invalid_required"

# Handler-side events emitted by real (non-placeholder) tool handlers.
# Every service-shim handler logs one of these; the ``MCP_SERVER_*`` set
# above covers the invoker layer.  ``MCP_HANDLER_NOT_IMPLEMENTED`` is
# declared once at the ``MCP_SERVER_INVOKE_*`` block above.
MCP_HANDLER_INVOKE_SUCCESS: Final[str] = "mcp.handler.invoke_success"
MCP_HANDLER_INVOKE_FAILED: Final[str] = "mcp.handler.invoke_failed"
MCP_HANDLER_GUARDRAIL_VIOLATED: Final[str] = "mcp.handler.guardrail_violated"
MCP_HANDLER_ARGUMENT_INVALID: Final[str] = "mcp.handler.argument_invalid"
MCP_HANDLER_SERVICE_FALLBACK: Final[str] = "mcp.handler.service_fallback"
MCP_HANDLER_CAPABILITY_GAP: Final[str] = "mcp.handler.capability_gap"
MCP_HANDLER_LAZY_SERVICE_INIT: Final[str] = "mcp.handler.lazy_service_init"
MCP_HANDLER_OUTCOME: Final[str] = "mcp.handler.outcome"
MCP_ADMIN_OP_EXECUTED: Final[str] = "mcp.admin_op.executed"
