"""Event constants for web tool operations."""

from typing import Final

WEB_REQUEST_START: Final[str] = "web.request.start"
WEB_REQUEST_SUCCESS: Final[str] = "web.request.success"
WEB_REQUEST_FAILED: Final[str] = "web.request.failed"
WEB_REQUEST_TIMEOUT: Final[str] = "web.request.timeout"
WEB_SSRF_BLOCKED: Final[str] = "web.ssrf.blocked"
WEB_HOSTNAME_CANONICALIZED: Final[str] = "web.hostname.canonicalized"
WEB_DNS_PIN_MISMATCH: Final[str] = "web.dns.pin_mismatch"
WEB_SSRF_DISABLED: Final[str] = "web.ssrf.disabled"
WEB_DNS_FAILED: Final[str] = "web.dns.failed"
WEB_SEARCH_START: Final[str] = "web.search.start"
WEB_SEARCH_SUCCESS: Final[str] = "web.search.success"
WEB_SEARCH_FAILED: Final[str] = "web.search.failed"
WEB_SEARCH_RETRY: Final[str] = "web.search.retry"
WEB_SEARCH_PROVIDER_BOUND: Final[str] = "web.search.provider_bound"
WEB_PARSE_START: Final[str] = "web.parse.start"
WEB_PARSE_SUCCESS: Final[str] = "web.parse.success"
WEB_PARSE_FAILED: Final[str] = "web.parse.failed"
WEB_FETCH_START: Final[str] = "web.fetch.start"
WEB_FETCH_SUCCESS: Final[str] = "web.fetch.success"
WEB_FETCH_FAILED: Final[str] = "web.fetch.failed"
WEB_FETCH_RETRY: Final[str] = "web.fetch.retry"
WEB_FETCH_EMPTY: Final[str] = "web.fetch.empty"
WEB_FETCH_EXTRACT_FAILED: Final[str] = "web.fetch.extract_failed"
WEB_FETCH_PROVIDER_BOUND: Final[str] = "web.fetch.provider_bound"
WEB_FETCH_BACKEND_UNAVAILABLE: Final[str] = "web.fetch.backend_unavailable"
WEB_LLMS_TXT_DISCOVERED: Final[str] = "web.llms_txt.discovered"
WEB_LLMS_TXT_ABSENT: Final[str] = "web.llms_txt.absent"
WEB_RESEARCH_READINESS: Final[str] = "web.research.readiness"
WEB_RESEARCH_CONNECTION_SCAN_FAILED: Final[str] = "web.research.connection_scan_failed"
