"""Improvement proposal models for the meta-loop.

The proposal rationale and the central :class:`ImprovementProposal`
that an ``ImprovementStrategy`` generates, a ``ProposalGuard`` validates,
and a ``ProposalApplier`` applies after mandatory human approval. The
proposal enforces an altitude/changes consistency invariant.
"""

from datetime import UTC, datetime
from typing import Self
from uuid import UUID, uuid4

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    computed_field,
    model_validator,
)

from synthorg.core.types import NotBlankStr
from synthorg.meta._change_models import (
    ArchitectureChange,
    CodeChange,
    ConfigChange,
    PromptChange,
    RollbackPlan,
)
from synthorg.meta._model_enums import (
    ProposalAltitude,
    ProposalStatus,
    RolloutStrategyType,
)
from synthorg.meta._proposal_altitude_descriptor import (
    ALTITUDE_PAYLOAD_FIELDS,
    PROPOSAL_ALTITUDE_DESCRIPTORS,
)
from synthorg.meta.toolsmith.models import ToolBlueprint


class ProposalRationale(BaseModel):
    """Evidence and reasoning behind an improvement proposal.

    Attributes:
        signal_summary: Key signals that motivated this proposal.
        pattern_detected: The pattern or issue identified.
        expected_impact: What improvement is expected.
        confidence_reasoning: Why the confidence level was assigned.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False, extra="forbid")

    signal_summary: NotBlankStr
    pattern_detected: NotBlankStr
    expected_impact: NotBlankStr
    confidence_reasoning: NotBlankStr


class ImprovementProposal(BaseModel):
    """A proposed improvement to the company deployment.

    Generated by an ``ImprovementStrategy``, validated by
    ``ProposalGuard``(s), and applied via a ``ProposalApplier``
    after mandatory human approval.

    Attributes:
        id: Unique proposal identifier.
        altitude: Which altitude of change this targets.
        title: Short human-readable title.
        description: Detailed description of the proposed change.
        rationale: Evidence and reasoning.
        config_changes: Config field changes (config_tuning altitude).
        architecture_changes: Structural changes (architecture altitude).
        prompt_changes: Prompt policy changes (prompt_tuning altitude).
        code_changes: Source file changes (code_modification altitude).
        rollback_plan: Concrete rollback plan.
        rollout_strategy: How to deploy the change.
        confidence: Strategy's confidence in this proposal (0-1).
        source_rule: Name of the rule that triggered this proposal.
        status: Lifecycle status.
        proposed_at: When the proposal was generated.
        decided_at: When the proposal was approved/rejected.
        decided_by: Who approved/rejected the proposal.
        decision_reason: Reason for approval/rejection.
        observation_window_hours: Post-apply observation window.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False, extra="forbid")

    id: UUID = Field(default_factory=uuid4)
    altitude: ProposalAltitude
    title: NotBlankStr
    description: NotBlankStr
    rationale: ProposalRationale
    config_changes: tuple[ConfigChange, ...] = ()
    architecture_changes: tuple[ArchitectureChange, ...] = ()
    prompt_changes: tuple[PromptChange, ...] = ()
    code_changes: tuple[CodeChange, ...] = ()
    tool_changes: tuple[ToolBlueprint, ...] = ()
    rollback_plan: RollbackPlan
    rollout_strategy: RolloutStrategyType = RolloutStrategyType.BEFORE_AFTER
    confidence: float = Field(ge=0.0, le=1.0)
    source_rule: NotBlankStr | None = None
    status: ProposalStatus = ProposalStatus.PENDING
    proposed_at: AwareDatetime = Field(
        default_factory=lambda: datetime.now(UTC),
    )
    decided_at: AwareDatetime | None = None
    decided_by: NotBlankStr | None = None
    decision_reason: NotBlankStr | None = None
    observation_window_hours: int = Field(default=48, ge=1)

    @model_validator(mode="after")
    def _validate_decision_consistency(self) -> Self:
        """Ensure decided_at/decided_by/decision_reason are all-or-nothing.

        Returns:
            ``Self`` instance.

        Raises:
            ValueError: Raised on the corresponding failure path.
        """
        decided = (self.decided_at, self.decided_by, self.decision_reason)
        if any(decided) and not all(decided):
            msg = (
                "decided_at, decided_by, and decision_reason "
                "must all be set or all be None"
            )
            raise ValueError(msg)
        terminal = {
            ProposalStatus.APPROVED,
            ProposalStatus.REJECTED,
            ProposalStatus.APPLIED,
        }
        if self.status in terminal and not all(decided):
            msg = "non-pending proposals must include decision metadata"
            raise ValueError(msg)
        return self

    @model_validator(mode="after")
    def _validate_changes_match_altitude(self) -> Self:
        """Ensure only the declared altitude carries changes.

        Drives off :data:`PROPOSAL_ALTITUDE_DESCRIPTORS`: the altitude's
        declared payload field must be populated and every other payload
        field must be empty. A new altitude without a descriptor fails at
        import (the descriptor module's completeness guard), not here.

        Returns:
            ``Self`` instance.

        Raises:
            ValueError: Raised on the corresponding failure path.
        """
        descriptor = PROPOSAL_ALTITUDE_DESCRIPTORS[self.altitude]
        declared = getattr(self, descriptor.payload_field)
        others_present = any(
            getattr(self, field)
            for field in ALTITUDE_PAYLOAD_FIELDS
            if field != descriptor.payload_field
        )
        if not declared or others_present:
            msg = (
                f"{self.altitude.value} proposals must contain only "
                f"{descriptor.payload_field}"
            )
            raise ValueError(msg)
        return self

    @computed_field  # type: ignore[prop-decorator]
    @property
    def change_count(self) -> int:
        """Total number of changes across all altitudes.

        Returns:
            Resulting integer.
        """
        return (
            len(self.config_changes)
            + len(self.architecture_changes)
            + len(self.prompt_changes)
            + len(self.code_changes)
            + len(self.tool_changes)
        )
