"""Setting definitions for all namespaces.

Importing this package triggers registration of all setting
definitions into the global :func:`~synthorg.settings.registry.get_registry`.
"""

from synthorg.settings.definitions import (
    a2a,
    api,
    appearance,
    backup,
    budget,
    charter,
    client,
    cockpit,
    communication,
    company,
    coordination,
    dashboard,
    demo,
    engine,
    external_api,
    hr,
    integrations,
    memory,
    meta,
    notifications,
    objectives,
    observability,
    org_chart,
    providers,
    research,
    security,
    settings,
    simulations,
    telemetry,
    tools,
    workers,
)

__all__ = [
    "a2a",
    "api",
    "appearance",
    "backup",
    "budget",
    "charter",
    "client",
    "cockpit",
    "communication",
    "company",
    "coordination",
    "dashboard",
    "demo",
    "engine",
    "external_api",
    "hr",
    "integrations",
    "memory",
    "meta",
    "notifications",
    "objectives",
    "observability",
    "org_chart",
    "providers",
    "research",
    "security",
    "settings",
    "simulations",
    "telemetry",
    "tools",
    "workers",
]
