/**
 * Route path constants -- single source of truth for all URL paths.
 *
 * Used by the router configuration, sidebar navigation, route guards,
 * and programmatic navigation throughout the dashboard.
 */
export const ROUTES = {
  DASHBOARD: '/',
  LOGIN: '/login',
  SETUP: '/setup',
  SETUP_STEP: '/setup/:step',
  MISSION_CONTROL: '/mission-control',
  ORG: '/org',
  ORG_EDIT: '/org/edit',
  TASKS: '/tasks',
  TASK_DETAIL: '/tasks/:taskId',
  BUDGET: '/budget',
  BUDGET_FORECAST: '/budget/forecast',
  REPORTS: '/reports',
  APPROVALS: '/approvals',
  SCALING: '/scaling',
  META: '/meta',
  CHARTERS: '/meta/charters',
  AGENTS: '/agents',
  AGENT_DETAIL: '/agents/:agentId',
  TRAINING: '/training',
  MESSAGES: '/messages',
  MEETINGS: '/meetings',
  MEETING_DETAIL: '/meetings/:meetingId',
  PROVIDERS: '/providers',
  PROVIDER_DETAIL: '/providers/:providerName',
  PROJECTS: '/projects',
  PROJECT_DETAIL: '/projects/:projectId',
  PROJECT_DOCS: '/projects/:projectId/docs',
  PROJECT_DOC_DETAIL: '/projects/:projectId/docs/:slug',
  ARTIFACTS: '/artifacts',
  ARTIFACT_DETAIL: '/artifacts/:artifactId',
  WORKFLOWS: '/workflows',
  WORKFLOW_EDITOR: '/workflows/editor',
  WORKFLOW_EXECUTIONS: '/workflows/:id/executions',
  WORKFLOW_VERSIONS: '/workflows/:id/versions',
  SUBWORKFLOWS: '/subworkflows',
  WEBHOOK_RECEIPTS: '/integrations/webhooks/receipts',
  COORDINATION_METRICS: '/analytics/coordination',
  META_ANALYTICS: '/analytics/meta',
  PERSONALITIES_ADMIN: '/admin/personalities',
  ADMIN_AUDIT_LOG: '/admin/audit',
  BUDGET_VERSIONS: '/budget/versions',
  COMPANY_VERSIONS: '/org/versions',
  EVALUATION_VERSIONS: '/evaluation/versions',
  ONTOLOGY: '/ontology',
  CUSTOM_RULES: '/meta/custom-rules',
  ESCALATIONS: '/conflicts/escalations',
  USERS: '/settings/users',
  CONNECTIONS: '/connections',
  OAUTH_APPS: '/integrations/oauth-apps',
  MCP_CATALOG: '/integrations/mcp-catalog',
  SETTINGS: '/settings',
  SETTINGS_NAMESPACE: '/settings/:namespace',
  SETTINGS_SINKS: '/settings/observability/sinks',
  SETTINGS_CEREMONY_POLICY: '/settings/coordination/ceremony-policy',
  SETTINGS_FINE_TUNING: '/settings/memory/fine-tuning',
  DOCUMENTATION: '/docs/',
  CLIENTS: '/clients',
  CLIENT_DETAIL: '/clients/:clientId',
  REQUEST_QUEUE: '/clients/requests',
  SIMULATION_DASHBOARD: '/clients/simulations',
  REVIEW_PIPELINE_VIEW: '/clients/reviews/:taskId',
} as const
