from contextlib import AbstractContextManager

from yoyo.migrations import MigrationList

class _Connection:
    def close(self) -> None: ...

class Backend:
    connection: _Connection
    def lock(self, timeout: int = ...) -> AbstractContextManager[None]: ...
    def to_apply(self, migrations: MigrationList) -> MigrationList: ...
    def to_rollback(self, migrations: MigrationList) -> MigrationList: ...
    def apply_migrations(
        self, migrations: MigrationList, force: bool = ...
    ) -> None: ...
    def mark_migrations(self, migrations: MigrationList) -> None: ...
    def rollback_migrations(
        self, migrations: MigrationList, force: bool = ...
    ) -> None: ...
    def break_lock(self) -> None: ...

def read_migrations(*sources: str) -> MigrationList: ...
def get_backend(uri: str, migration_table: str = ...) -> Backend: ...
