"""Type stubs for ``yoyo.backends``: the DB backend the runner drives."""

from contextlib import AbstractContextManager

from yoyo.migrations import MigrationList

class Backend:
    def lock(self, timeout: int = ...) -> AbstractContextManager[object]: ...
    def to_apply(self, migrations: MigrationList) -> MigrationList: ...
    def to_rollback(self, migrations: MigrationList) -> MigrationList: ...
    def apply_migrations(self, migrations: MigrationList) -> None: ...
    def rollback_migrations(self, migrations: MigrationList) -> None: ...
    def mark_migrations(self, migrations: MigrationList) -> None: ...
    def break_lock(self) -> None: ...
