// AUTO-GENERATED: do not edit by hand.
// Regenerate with: uv run python scripts/generate_backend_enums_ts.py
// Drift check (pre-push): uv run python scripts/check_backend_enums_ts_in_sync.py
// Sources: src/synthorg/api/ws_models.py, src/synthorg/notifications/models.py, src/synthorg/observability/enums.py, src/synthorg/providers/health.py

export const WS_EVENT_TYPE_VALUES = [
  "task.created",
  "task.updated",
  "task.status_changed",
  "task.assigned",
  "agent.hired",
  "agent.fired",
  "agent.status_changed",
  "agent.created",
  "agent.updated",
  "agent.deleted",
  "agents.reordered",
  "company.updated",
  "department.created",
  "department.updated",
  "department.deleted",
  "departments.reordered",
  "personality.trimmed",
  "budget.record_added",
  "budget.alert",
  "message.sent",
  "system.error",
  "system.startup",
  "system.shutdown",
  "approval.submitted",
  "approval.approved",
  "approval.rejected",
  "approval.expired",
  "coordination.started",
  "coordination.phase_completed",
  "coordination.completed",
  "coordination.failed",
  "meeting.started",
  "meeting.completed",
  "meeting.failed",
  "artifact.created",
  "artifact.deleted",
  "artifact.content_uploaded",
  "project.created",
  "project.deleted",
  "project.autonomy_mode_changed",
  "project.status_changed",
  "plan.updated",
  "plan.changes_requested",
  "plan.comment_added",
  "workflow_execution.status_changed",
  "memory.fine_tune.progress",
  "memory.fine_tune.stage_changed",
  "memory.fine_tune.completed",
  "memory.fine_tune.failed",
  "client.created",
  "client.updated",
  "client.deactivated",
  "client.deleted",
  "request.submitted",
  "request.scoped",
  "request.approved",
  "request.task_created",
  "request.rejected",
  "request.status_changed",
  "simulation.started",
  "simulation.running",
  "simulation.paused",
  "simulation.cancelled",
  "simulation.completed",
  "simulation.failed",
  "review.stage_completed",
  "review.stage_decided",
  "review.pipeline_completed",
  "interrupt.created",
  "interrupt.resumed",
  "dissent.published",
  "steering.directive.issued",
  "steering.supersession.proposed",
  "steering.tasks.superseded",
] as const
export type WsEventType = (typeof WS_EVENT_TYPE_VALUES)[number]

export const NOTIFICATION_SEVERITY_VALUES = [
  "info",
  "warning",
  "error",
  "critical",
] as const
export type NotificationSeverity = (typeof NOTIFICATION_SEVERITY_VALUES)[number]

export const LOG_LEVEL_VALUES = [
  "DEBUG",
  "INFO",
  "WARNING",
  "ERROR",
  "CRITICAL",
] as const
export type LogLevel = (typeof LOG_LEVEL_VALUES)[number]

export const PROVIDER_OUTCOME_CLASS_VALUES = [
  "success",
  "rate_limit",
  "quota_exceeded",
  "payment_required",
  "timeout",
  "connection",
  "internal",
  "overloaded",
  "invalid_request",
  "auth",
  "content_filter",
  "not_found",
  "other",
] as const
export type ProviderOutcomeClass = (typeof PROVIDER_OUTCOME_CLASS_VALUES)[number]
