"""Validation + PR-body helpers for the code applier.

Proposal-shape rejection, per-change filesystem precondition checks
for dry-run, and the draft-PR body builder. Pure functions with no
filesystem mutation (preconditions only read).
"""

from pathlib import Path
from typing import Final

from synthorg.meta.models import (
    ApplyResult,
    CodeChange,
    CodeOperation,
    ImprovementProposal,
    ProposalAltitude,
)

_MAX_PR_BODY_FIELD_CHARS: Final[int] = 2_000


def _check_proposal_shape(
    proposal: ImprovementProposal,
) -> ApplyResult | None:
    """Reject proposals with wrong altitude or no changes.

    Args:
        proposal: The proposal to validate.

    Returns:
        A failure ApplyResult if invalid, or None if OK.
    """
    if proposal.altitude != ProposalAltitude.CODE_MODIFICATION:
        return ApplyResult(
            success=False,
            error_message=(
                f"Expected CODE_MODIFICATION altitude, got {proposal.altitude.value}"
            ),
            changes_applied=0,
        )
    if not proposal.code_changes:
        return ApplyResult(
            success=False,
            error_message="Proposal has no code changes",
            changes_applied=0,
        )
    return None


def _validate_change_preconditions(
    change: CodeChange,
    file_path: Path,
    errors: list[str],
) -> None:
    """Check filesystem preconditions for a single code change.

    Args:
        change: The code change to validate.
        file_path: Resolved absolute path.
        errors: Mutable list to append error descriptions to.
    """
    if change.operation == CodeOperation.MODIFY:
        if not file_path.exists():
            errors.append(
                f"MODIFY target does not exist: {change.file_path}",
            )
        else:
            current = file_path.read_text(encoding="utf-8")
            if current != change.old_content:
                errors.append(
                    f"MODIFY target changed since proposal: {change.file_path}",
                )
    elif change.operation == CodeOperation.DELETE:
        if not file_path.exists():
            errors.append(
                f"DELETE target does not exist: {change.file_path}",
            )
        else:
            current = file_path.read_text(encoding="utf-8")
            if current != change.old_content:
                errors.append(
                    f"DELETE target changed since proposal: {change.file_path}",
                )
    elif change.operation == CodeOperation.CREATE and file_path.exists():
        errors.append(
            f"CREATE target already exists: {change.file_path}",
        )


def _bound_field(text: str) -> str:
    """Bound an LLM-authored free-text field embedded in the PR body.

    The signal summary and description are model output; capping their
    length keeps a runaway generation from producing an unbounded PR
    body. The mandatory human-review gate remains the control against
    malicious Markdown.

    Args:
        text: The free-text field value.

    Returns:
        The field, truncated with a marker when over the cap.
    """
    if len(text) <= _MAX_PR_BODY_FIELD_CHARS:
        return text
    return text[:_MAX_PR_BODY_FIELD_CHARS] + "\n\n*(truncated)*"


def _build_pr_body(proposal: ImprovementProposal) -> str:
    """Build the PR body from a proposal.

    Args:
        proposal: The proposal to describe.

    Returns:
        Markdown-formatted PR body.
    """
    return (
        f"## Meta-Loop Code Modification\n\n"
        f"**Proposal ID**: {proposal.id}\n"
        f"**Source Rule**: {proposal.source_rule}\n"
        f"**Confidence**: {proposal.confidence:.0%}\n\n"
        f"### Rationale\n\n"
        f"{_bound_field(proposal.rationale.signal_summary)}\n\n"
        f"### Changes\n\n"
        f"{_bound_field(proposal.description)}\n\n"
        f"---\n"
        f"*Auto-generated by the self-improvement meta-loop. "
        f"Human review required before merge.*"
    )
