"""Envelope construction and revision helpers for the project brain.

Pure functions that build and re-validate :class:`BrainEntry` envelopes. They
carry no service state: the caller passes the ``now`` timestamp (from the
service's clock seam) so these stay deterministic and unit-testable in
isolation. Keeping them here keeps :class:`ProjectBrainService` orchestration-
only and within the service-tier size budget.

Both functions translate Pydantic ``ValidationError`` into the domain
:class:`BrainEntryValidationError`, so the service never leaks the raw library
error across its boundary.
"""

from datetime import datetime

from pydantic import ValidationError

from synthorg.core.types import NotBlankStr
from synthorg.project_brain.errors import BrainEntryValidationError
from synthorg.project_brain.models import (
    BrainEntry,
    BrainEntryStatus,
    BrainPayloadValue,
    Citation,
)


def build_entry(  # noqa: PLR0913 -- envelope fields are explicit
    *,
    now: datetime,
    project_id: NotBlankStr,
    title: NotBlankStr,
    rationale: NotBlankStr,
    status: BrainEntryStatus,
    author: NotBlankStr,
    payload: BrainPayloadValue,
    related_task_ids: tuple[NotBlankStr, ...],
    related_entry_ids: tuple[NotBlankStr, ...],
    supersedes_entry_id: NotBlankStr | None,
    tags: tuple[NotBlankStr, ...],
    confidence: float | None,
    citations: tuple[Citation, ...],
) -> BrainEntry:
    """Construct and validate a fresh revision-1 envelope.

    The entry kind is taken from ``payload.entry_kind``; a fresh logical
    ``entry_id`` is generated by the model default. The ``revision`` field is
    left at its placeholder default; the repository assigns the real value on
    append.

    Args:
        now: Timestamp to stamp as ``recorded_at`` (from the service clock).
        project_id: Owning project.
        title: Human-readable title.
        rationale: Why the entry holds (the "why").
        status: Lifecycle status; validated against the kind.
        author: Agent id or operator id of the writer.
        payload: The kind-specific discriminated payload.
        related_task_ids: Task IDs this entry references.
        related_entry_ids: Other brain entry IDs this entry references.
        supersedes_entry_id: The entry id this one supersedes, if any.
        tags: Free-form classification tags (unique).
        confidence: Optional confidence in ``[0, 1]``.
        citations: Provenance pointers backing this entry.

    Returns:
        The validated entry (revision left at the placeholder default).

    Raises:
        BrainEntryValidationError: If the envelope fails validation.
    """
    try:
        return BrainEntry(
            project_id=project_id,
            entry_kind=payload.entry_kind,
            title=title,
            rationale=rationale,
            status=status,
            author=author,
            recorded_at=now,
            related_task_ids=related_task_ids,
            related_entry_ids=related_entry_ids,
            supersedes_entry_id=supersedes_entry_id,
            tags=tags,
            confidence=confidence,
            citations=citations,
            payload=payload,
        )
    except ValidationError as exc:
        msg = "brain entry failed validation"
        raise BrainEntryValidationError(msg) from exc


def apply_overrides(  # noqa: PLR0913 -- optional overrides are explicit
    current: BrainEntry,
    *,
    now: datetime,
    author: NotBlankStr,
    status: BrainEntryStatus | None = None,
    title: NotBlankStr | None = None,
    rationale: NotBlankStr | None = None,
    payload: BrainPayloadValue | None = None,
    related_task_ids: tuple[NotBlankStr, ...] | None = None,
    related_entry_ids: tuple[NotBlankStr, ...] | None = None,
    supersedes_entry_id: NotBlankStr | None = None,
    tags: tuple[NotBlankStr, ...] | None = None,
    citations: tuple[Citation, ...] | None = None,
) -> BrainEntry:
    """Apply overrides to *current*, re-stamp, and re-validate.

    Every supplied override replaces the corresponding field; omitted fields
    inherit the current revision's value (including ``confidence``). The
    ``revision`` placeholder is reset to the default so the repository assigns
    the next value. The candidate is round-tripped through ``model_validate`` so
    an illegal status-for-kind transition is rejected (``model_copy`` alone does
    not re-run validators).

    Args:
        current: The latest revision being revised.
        now: Timestamp to stamp as ``recorded_at`` (from the service clock).
        author: Who is making this revision.
        status: New status, or ``None`` to keep.
        title: New title, or ``None`` to keep.
        rationale: New rationale, or ``None`` to keep.
        payload: New payload (same kind), or ``None`` to keep.
        related_task_ids: Replacement task links, or ``None`` to keep.
        related_entry_ids: Replacement entry links, or ``None`` to keep.
        supersedes_entry_id: New supersession link, or ``None`` to keep.
        tags: Replacement tags, or ``None`` to keep.
        citations: Replacement citations, or ``None`` to keep.

    Returns:
        The validated next-revision envelope.

    Raises:
        BrainEntryValidationError: If the revised envelope fails validation.
    """
    updates: dict[str, object] = {
        "author": author,
        "recorded_at": now,
        "revision": 1,
    }
    if status is not None:
        updates["status"] = status
    if title is not None:
        updates["title"] = title
    if rationale is not None:
        updates["rationale"] = rationale
    if payload is not None:
        updates["payload"] = payload
    if related_task_ids is not None:
        updates["related_task_ids"] = related_task_ids
    if related_entry_ids is not None:
        updates["related_entry_ids"] = related_entry_ids
    if supersedes_entry_id is not None:
        updates["supersedes_entry_id"] = supersedes_entry_id
    if tags is not None:
        updates["tags"] = tags
    if citations is not None:
        updates["citations"] = citations
    candidate = current.model_copy(update=updates)
    try:
        return BrainEntry.model_validate(candidate.model_dump(mode="json"))
    except ValidationError as exc:
        msg = "revised brain entry failed validation"
        raise BrainEntryValidationError(msg) from exc
