# module-kind: code
"""Injectable hook contracts for the structured-phases meeting protocol.

The consensus-velocity and premortem hooks are structurally typed in the
meeting package so the strategy subsystem (``engine.strategy.*``) can be
injected without ``communication.meeting`` importing ``engine.strategy``
(which would close an import cycle: the strategy package already depends
on the meeting package). The api layer binds the concrete detectors and
their config behind these signatures.

Kept in a sibling module (rather than inline in ``structured_phases``) so
the protocol implementation stays within its module-size budget.
"""

from typing import Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field

from synthorg.communication.meeting.protocol import AgentCaller


@runtime_checkable
class ConsensusVelocityHook(Protocol):
    """Premature-consensus check over the gathered input positions.

    Structurally typed in the meeting package so the strategy
    subsystem (``engine.strategy.consensus``) can be injected without
    ``communication.meeting`` importing ``engine.strategy`` (which would
    close an import cycle: the strategy package already depends on the
    meeting package). The api layer binds the concrete
    ``ConsensusVelocityDetector`` + its config behind this signature.
    """

    def __call__(self, positions: tuple[str, ...]) -> bool:
        """Return whether the positions show premature consensus."""
        ...


class PremortemHookResult(BaseModel):
    """Rendered premortem section plus the tokens it consumed.

    The hook runs LLM agent calls via ``agent_caller``; returning the
    usage (not just the text) lets the meeting layer, which owns the
    ``TokenTracker``, fold premortem consumption into the meeting budget
    and the minutes' totals rather than silently dropping it.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False, extra="forbid")

    text: str = Field(
        description="Rendered premortem section (empty when nothing surfaced).",
    )
    input_tokens: int = Field(
        default=0,
        ge=0,
        description="Prompt tokens consumed by the premortem agent calls.",
    )
    output_tokens: int = Field(
        default=0,
        ge=0,
        description="Response tokens generated by the premortem agent calls.",
    )


@runtime_checkable
class PremortemHook(Protocol):
    """Premortem analysis over the synthesis summary.

    Returns the rendered premortem section text plus the token usage it
    incurred (see :class:`PremortemHookResult`); the text is empty when
    no failure modes / assumptions surfaced. Structurally typed for the
    same cycle-avoidance reason as :class:`ConsensusVelocityHook`.
    """

    async def __call__(
        self,
        *,
        synthesis_text: str,
        participant_ids: tuple[str, ...],
        agent_caller: AgentCaller,
        token_budget: int,
        context_id: str,
    ) -> PremortemHookResult:
        """Run premortem and return the rendered section plus token usage."""
        ...
