package cmd

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/spf13/cobra"

	"github.com/Aureliolo/synthorg/cli/internal/config"
	"github.com/Aureliolo/synthorg/cli/internal/docker"
)

// pullAndPersistTestState builds a config.State that ParamsFromState/
// Generate (invoked indirectly through writeOrPatchCompose) accept, with a
// nonexistent docker/compose binary so pullAllImages fails immediately and
// deterministically without a real Docker daemon or network access.
func pullAndPersistTestState(dir string) config.State {
	return config.State{
		DataDir:            dir,
		ImageTag:           "0.9.0",
		BackendPort:        3001,
		WebPort:            3000,
		LogLevel:           "info",
		PersistenceBackend: "sqlite",
		MemoryBackend:      "sqlvector",
		BusBackend:         "internal",
	}
}

func nonexistentDockerInfo() docker.Info {
	const missingBinary = "synthorg-test-nonexistent-docker-binary"
	return docker.Info{
		DockerPath: missingBinary,
		ComposeCmd: []string{missingBinary, "compose"},
	}
}

func newPullTestCmd(ctx context.Context) *cobra.Command {
	cmd := &cobra.Command{}
	cmd.SetContext(ctx)
	cmd.SetOut(new(bytes.Buffer))
	cmd.SetErr(new(bytes.Buffer))
	return cmd
}

// TestPullAndPersist_RollbackOnPullFailure is a regression test for the
// rollback mechanism pullAndPersist depends on: it writes compose.yml with
// the new image pins before the pull runs, and must roll it back to its
// prior contents -- never persisting config.json -- when the pull fails.
// This exercises the real pullAndPersist/composeRollback/config.Save code
// path end to end; only the docker/compose binary is faked out, so the
// pull fails immediately without a real Docker daemon.
func TestPullAndPersist_RollbackOnPullFailure(t *testing.T) {
	dir := t.TempDir()
	const originalCompose = "# Generated by SynthOrg CLI v0.9.0\nservices:\n  backend:\n    image: ghcr.io/aureliolo/synthorg-backend:0.9.0\n"
	composePath := filepath.Join(dir, "compose.yml")
	if err := os.WriteFile(composePath, []byte(originalCompose), 0o600); err != nil {
		t.Fatalf("setup: %v", err)
	}

	ctx := SetGlobalOpts(context.Background(), &GlobalOpts{
		SkipVerify: true, // bypass network cosign verification for this test
		Hints:      "auto",
		Tunables:   config.DefaultTunables(),
	})
	cmd := newPullTestCmd(ctx)

	_, err := pullAndPersist(ctx, cmd, nonexistentDockerInfo(), pullAndPersistTestState(dir), "0.9.1", dir, false)
	if err == nil {
		t.Fatal("expected pullAndPersist to fail when the compose binary does not exist")
	}

	gotCompose, readErr := os.ReadFile(composePath)
	if readErr != nil {
		t.Fatalf("reading compose.yml after rollback: %v", readErr)
	}
	if string(gotCompose) != originalCompose {
		t.Errorf("compose.yml was not rolled back to its original contents.\nwant:\n%s\ngot:\n%s", originalCompose, gotCompose)
	}

	if _, statErr := os.Stat(config.StatePath(dir)); statErr == nil {
		t.Error("config.json should not have been written after a failed pull")
	} else if !os.IsNotExist(statErr) {
		t.Errorf("unexpected error checking config.json: %v", statErr)
	}
}

// TestPullAndPersist_RollbackOnCancelledContext is the interrupt-specific
// variant of the above: a context already cancelled before the pull starts
// (simulating cmd.Execute's signal.NotifyContext having already fired)
// must still trigger the same rollback. This is what closes the gap the
// generic pull-failure test above cannot: it proves that Ctrl+C during a
// pull reaching pullAndPersist's existing rollback branch actually works,
// not merely that some other kind of pull failure does.
func TestPullAndPersist_RollbackOnCancelledContext(t *testing.T) {
	dir := t.TempDir()
	const originalCompose = "# Generated by SynthOrg CLI v0.9.0\nservices:\n  backend:\n    image: ghcr.io/aureliolo/synthorg-backend:0.9.0\n"
	composePath := filepath.Join(dir, "compose.yml")
	if err := os.WriteFile(composePath, []byte(originalCompose), 0o600); err != nil {
		t.Fatalf("setup: %v", err)
	}

	optsCtx := SetGlobalOpts(context.Background(), &GlobalOpts{
		SkipVerify: true,
		Hints:      "auto",
		Tunables:   config.DefaultTunables(),
	})
	pullCtx, cancel := context.WithCancel(optsCtx)
	cancel() // simulate cmd.Execute's signal handler having already fired

	cmd := newPullTestCmd(pullCtx)

	_, err := pullAndPersist(pullCtx, cmd, nonexistentDockerInfo(), pullAndPersistTestState(dir), "0.9.1", dir, false)
	if err == nil {
		t.Fatal("expected pullAndPersist to fail against an already-cancelled context")
	}

	gotCompose, readErr := os.ReadFile(composePath)
	if readErr != nil {
		t.Fatalf("reading compose.yml after rollback: %v", readErr)
	}
	if string(gotCompose) != originalCompose {
		t.Errorf("compose.yml was not rolled back after a cancelled-context pull.\nwant:\n%s\ngot:\n%s", originalCompose, gotCompose)
	}
}
