#!/usr/bin/env python3
"""Pre-push / CI gate: keep developer rationale out of the generated compose.

``cli/internal/compose/compose.yml.tmpl`` renders the compose file an
operator runs their stack from, and it carries two comment forms that
look alike and behave completely differently:

* ``{{- /* ... */}}`` is a Go template comment. It stays in the repo
  and never reaches the generated file.
* ``#`` is a YAML comment. It is copied verbatim into the operator's
  ``compose.yml``.

The template's own header declares the split -- rationale goes in the
first form, and the second is reserved for the few warnings that are
worth something to somebody editing a file they were told not to edit.
Nothing enforced it, and the shipping side drifted until the rule was
the exception: of 20 comment lines in the generated default stack, 2
passed it. The largest block was a ten-line note naming three PRIVATE
Python constants an operator cannot open, ending with an instruction
addressed to a developer, inside a file whose second line says do not
edit manually.

Rationale that ships costs more than the lines. The CLI diffs the
generated file on update and asks the operator to approve the change,
so a pure-prose edit becomes a prompt: one such diff was eleven lines
of which nine were comment. Every one of those trains the operator to
click through a diff they cannot evaluate, and the broken line wrap
this gate was written alongside reached exactly that prompt.

So every shipping block is declared here, with the audience it serves.
A block with no declaration fails, and a declaration matching no block
fails too -- an allowance that outlives its comment is the one the
next comment inherits without anybody deciding. Blocks are also capped
at ``_MAX_BLOCK_LINES``: an operator warning that needs a paragraph
has stopped being a warning, which is the shape the ten-line block
arrived in.

Deliberately out of scope: ``docker/compose.yml``. It is hand-
maintained, read by the developers who edit it, and generates nothing,
so it has no second comment form to move rationale into and no
operator-facing diff to pollute. The WHY-only rule in CLAUDE.md
governs it, and review enforces that.

There is deliberately no per-line opt-out. A genuine exception is a
new row below, which is where the claim "this is for the operator"
gets written down.

Usage::

    python scripts/check_compose_template_comments.py
    python scripts/check_compose_template_comments.py --repo-root .

Exit codes:
    0 -- every shipping comment is declared and within the cap.
    1 -- an undeclared block, an oversized block, or a stale allowance.
    2 -- configuration error (bad ``--repo-root`` or unreadable template).
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Final, NamedTuple

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from _gate_source import (  # type: ignore[import-not-found]
        GateSourceError,
        read_source,
    )
else:
    from scripts._gate_source import GateSourceError, read_source

_TEMPLATE_REL: Final[str] = "cli/internal/compose/compose.yml.tmpl"

# Long enough for a warning, short enough that rationale cannot hide as
# one. Every declared block below fits; the ten-line shutdown note that
# prompted this gate does not.
_MAX_BLOCK_LINES: Final[int] = 5


class AllowedBlock(NamedTuple):
    """One sanctioned shipping comment block.

    Attributes:
        anchor: Distinctive text the block must contain. Matched as a
            substring against the block's joined body, so rewording
            around it is free and losing it is a decision.
        audience: Who the comment is for and what they can do about it.
            Printed when the declaration goes stale, because that is
            the moment somebody has to judge whether it still applies.
    """

    anchor: str
    audience: str


# Each row is a claim that the block reaches somebody who can act on
# it: an operator editing the file anyway, or one deciding whether to.
_ALLOWED_BLOCKS: Final[tuple[AllowedBlock, ...]] = (
    AllowedBlock(
        anchor="Generated by SynthOrg CLI",
        audience=(
            "anyone opening the file, who otherwise has no way to know "
            "their edits are overwritten by the next 'synthorg init'"
        ),
    ),
    AllowedBlock(
        anchor="root-equivalent access to the host Docker daemon",
        audience=(
            "an operator weighing the sandbox against handing the "
            "backend a socket the rest of the hardening does not contain"
        ),
    ),
    AllowedBlock(
        anchor="runs without TLS on the internal docker",
        audience=(
            "an operator taking this stack to production, where the "
            "shipped value is a weakened posture rather than a default"
        ),
    ),
    AllowedBlock(
        anchor="invalidates every outstanding pagination cursor",
        audience="an operator about to rotate the value on the line below",
    ),
    AllowedBlock(
        anchor="rotation is not supported",
        audience=(
            "an operator about to rotate a key whose loss makes every "
            "stored connection secret unreadable"
        ),
    ),
    AllowedBlock(
        anchor="the GID owning",
        audience=(
            "an operator moving the install to another host, where the "
            "value below is stale and the backend loses the socket"
        ),
    ),
    AllowedBlock(
        anchor="Uncomment to expose NATS monitoring",
        audience=(
            "an operator debugging the bus, who needs to know the port "
            "is unauthenticated before uncommenting the line"
        ),
    ),
)

# Go template comments in every spelling: '{{/* */}}', '{{- /* */}}',
# and either with a trailing '-}}'. Body is non-greedy so two adjacent
# blocks do not collapse into one match.
_TEMPLATE_COMMENT_RE: Final[re.Pattern[str]] = re.compile(
    r"\{\{-?\s*/\*.*?\*/\s*-?\}\}", re.DOTALL
)

_COMMENT_LINE_RE: Final[re.Pattern[str]] = re.compile(r"^\s*#")


class CommentBlock(NamedTuple):
    """A run of consecutive shipping comment lines.

    Attributes:
        start_line: 1-indexed line of the block's first comment line.
        lines: The raw source lines making up the block.
    """

    start_line: int
    lines: tuple[str, ...]

    @property
    def body(self) -> str:
        """The block's text with comment markers and indentation gone."""
        return " ".join(line.strip().lstrip("#").strip() for line in self.lines)


def _blank_template_comments(source: str) -> str:
    """Replace Go template comments with blank lines of equal count.

    A ``#`` inside a template comment never ships, so it must not be
    read as one. Substituting newlines rather than deleting the region
    keeps every following line at its real number, which is what the
    violation messages point at.

    Args:
        source: The raw template text.

    Returns:
        The text with every template-comment region blanked.
    """

    def _blank(match: re.Match[str]) -> str:
        return "\n" * match.group(0).count("\n")

    return _TEMPLATE_COMMENT_RE.sub(_blank, source)


def _comment_blocks(source: str) -> list[CommentBlock]:
    """Group the shipping comment lines into consecutive blocks.

    Args:
        source: Template text with template comments already blanked.

    Returns:
        Every run of adjacent ``#`` lines, in file order.
    """
    blocks: list[CommentBlock] = []
    current: list[str] = []
    start = 0
    for number, line in enumerate(source.splitlines(), start=1):
        if _COMMENT_LINE_RE.match(line):
            if not current:
                start = number
            current.append(line)
            continue
        if current:
            blocks.append(CommentBlock(start, tuple(current)))
            current = []
    if current:
        blocks.append(CommentBlock(start, tuple(current)))
    return blocks


def _check(repo_root: Path) -> list[str]:
    """Hold every shipping comment to a declaration and the size cap.

    Args:
        repo_root: Repository root the template is resolved against.

    Returns:
        A list of violation messages (empty when the template is clean).

    Raises:
        GateSourceError: The template is missing, unreadable, or has no
            shipping comment at all, which means the header vanished and
            the gate is reading the wrong file.
    """
    source = read_source(repo_root / _TEMPLATE_REL)
    blocks = _comment_blocks(_blank_template_comments(source))
    if not blocks:
        message = (
            f"{_TEMPLATE_REL}: no '#' comment found at all, so the "
            "generated-file header is gone and this gate is checking nothing"
        )
        raise GateSourceError(message)

    violations: list[str] = []
    matched: set[str] = set()
    for block in blocks:
        body = block.body
        anchors = [entry.anchor for entry in _ALLOWED_BLOCKS if entry.anchor in body]
        if not anchors:
            violations.append(
                f"{_TEMPLATE_REL}:{block.start_line}: undeclared '#' comment ships "
                f"to the operator's compose.yml -- move it into a "
                f"'{{{{- /* ... */}}}}' template comment, or declare it in "
                f"{Path(__file__).name} with the audience it serves: "
                f"{body[:80]!r}"
            )
            continue
        matched.update(anchors)
        if len(block.lines) > _MAX_BLOCK_LINES:
            violations.append(
                f"{_TEMPLATE_REL}:{block.start_line}: shipping comment is "
                f"{len(block.lines)} lines, over the {_MAX_BLOCK_LINES}-line cap "
                f"-- a warning this long has become rationale, which belongs in "
                f"a '{{{{- /* ... */}}}}' template comment"
            )

    violations.extend(
        f"{Path(__file__).name}: declared block {entry.anchor!r} matches "
        f"no comment in {_TEMPLATE_REL} -- delete the row, or restore the "
        f"comment, which was for {entry.audience}"
        for entry in _ALLOWED_BLOCKS
        if entry.anchor not in matched
    )
    return violations


def main() -> int:
    """Run the compose-template comment gate.

    Returns:
        The process exit code (0 clean, 1 violations, 2 config error).
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    try:
        violations = _check(args.repo_root)
    except GateSourceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if violations:
        print("Compose-template comment check failed:", file=sys.stderr)
        for violation in violations:
            print(f"  {violation}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
