"""Inventory hardcoded user-facing strings in the web dashboard.

Walks ``web/src/pages/`` and ``web/src/components/`` looking for
double- or single-quoted strings that look like user-facing copy
(at least 6 chars, contain a space, start with a letter, are not
imports / class names / hex literals / token paths / event names).

The output is two files in ``docs/internal/``:

* ``i18n-strings.md`` -- a Markdown summary keyed by file with the
  total string count and the top-10 most-strings pages.
* ``i18n-strings.json`` -- a machine-readable list keyed by file path
  with line numbers and the literal text.  Sorted deterministically
  so re-runs produce identical output.

This is the read-only artefact the i18n migration tracked under
issue #1417 will consume.  The script does NOT modify any source
file; the actual extraction-to-message-keys lives in #1417.
"""

import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_SRC = ROOT / "web" / "src"
OUT_DIR = ROOT / "docs" / "internal"
MIN_LENGTH = 6

# Capture quoted strings.  We match both single- and double-quoted
# literals.  The strict regex is intentional: it only fires on
# strings that contain at least one space and start with a letter,
# which filters out the bulk of CSS class names, dotted token paths
# and event-name string constants.
STRING_RE = re.compile(
    r"""(?P<quote>['"])(?P<body>[A-Z][^'"\n]*\s[^'"\n]*)(?P=quote)""",
    re.IGNORECASE,
)

EXCLUDED_DIRS = {"__tests__", "mocks", "stories"}
EXCLUDED_SUFFIXES = {".test.ts", ".test.tsx", ".stories.tsx", ".bench.ts"}

# Patterns we never report even when they match the regex.  These are
# almost always not user copy: aria-* and data-* attribute names,
# event names with colons, dotted ids, sentence-case strings that are
# just labels for class-name lookup tables, etc.
SUPPRESS_RE = re.compile(
    r"^(?:aria-|data-|chunk-|event-|test-|webpack)|"
    r"(?:[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+){2,}|"
    r"^[A-Z][a-z]+[A-Z]"  # CamelCase identifiers
)


def is_user_copy(text: str) -> bool:
    """Heuristic: does ``text`` look like a UI-facing string?"""
    if len(text) < MIN_LENGTH:
        return False
    if SUPPRESS_RE.search(text):
        return False
    return any(ch == " " for ch in text)


def walk_sources() -> list[Path]:
    """Return the deterministic list of TS/TSX files we scan."""
    out: list[Path] = []
    for p in WEB_SRC.rglob("*"):
        if not p.is_file():
            continue
        if p.suffix not in (".ts", ".tsx"):
            continue
        if any(part in EXCLUDED_DIRS for part in p.relative_to(WEB_SRC).parts):
            continue
        if any(p.name.endswith(suffix) for suffix in EXCLUDED_SUFFIXES):
            continue
        out.append(p)
    return sorted(out)


def extract(path: Path) -> list[tuple[int, str]]:
    """Extract ``(line, text)`` candidates from ``path``."""
    hits: list[tuple[int, str]] = []
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return hits
    for line_no, line in enumerate(text.splitlines(), start=1):
        # Skip lines that are entirely import / from / etc.
        stripped = line.lstrip()
        if stripped.startswith(("import ", "from ", "//")):
            continue
        for match in STRING_RE.finditer(line):
            body = match.group("body")
            if is_user_copy(body):
                hits.append((line_no, body))
    return hits


def main() -> int:
    """Run the inventory script: walk sources, write the two artefact files."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    by_file: dict[str, list[tuple[int, str]]] = defaultdict(list)
    for path in walk_sources():
        rel = path.relative_to(ROOT).as_posix()
        for line, body in extract(path):
            by_file[rel].append((line, body))

    total = sum(len(v) for v in by_file.values())
    top_pages = sorted(by_file.items(), key=lambda kv: len(kv[1]), reverse=True)[:10]

    # Markdown summary
    md_lines: list[str] = [
        "# Hardcoded user-facing strings inventory",
        "",
        (
            "Generated by ``scripts/inventory_i18n_strings.py``.  This is the "
            "read-only artefact the i18n migration tracked under issue "
            "#1417 will consume; do not hand-edit."
        ),
        "",
        f"**Total strings**: {total}",
        f"**Files scanned**: {sum(1 for _ in walk_sources())}",
        "",
        "## Top files by string count",
        "",
        "| File | Strings |",
        "| --- | --- |",
    ]
    for path, hits in top_pages:
        md_lines.append(f"| `{path}` | {len(hits)} |")
    md_lines.append("")
    md_lines.append("See ``i18n-strings.json`` for the full enumeration.")
    md_lines.append("")
    (OUT_DIR / "i18n-strings.md").write_text("\n".join(md_lines), encoding="utf-8")

    # JSON enumeration
    json_payload: dict[str, list[dict[str, object]]] = {}
    for path in sorted(by_file):
        json_payload[path] = [
            {"line": line, "text": body} for line, body in sorted(by_file[path])
        ]
    (OUT_DIR / "i18n-strings.json").write_text(
        json.dumps(json_payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {total} strings across {len(by_file)} files to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
