"""WCAG AA contrast ratio verification for the Warm Ops color palette.

Computes contrast ratios for all text/background color combinations and
outputs a markdown table with pass/fail status.

Usage:
    uv run python scripts/wcag_check.py
"""


def hex_to_rgb(hex_color: str) -> tuple[float, float, float]:
    """Convert hex color to normalized RGB (0-1 range)."""
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return r / 255.0, g / 255.0, b / 255.0


def relative_luminance(hex_color: str) -> float:
    """Compute WCAG 2.1 relative luminance.

    See https://www.w3.org/TR/WCAG21/#dfn-relative-luminance
    """
    r, g, b = hex_to_rgb(hex_color)

    srgb_threshold = 0.04045

    def linearize(c: float) -> float:
        return c / 12.92 if c <= srgb_threshold else ((c + 0.055) / 1.055) ** 2.4

    r_lin = linearize(r)
    g_lin = linearize(g)
    b_lin = linearize(b)
    return 0.2126 * r_lin + 0.7152 * g_lin + 0.0722 * b_lin


def contrast_ratio(fg: str, bg: str) -> float:
    """Compute WCAG contrast ratio between two colors."""
    l1 = relative_luminance(fg)
    l2 = relative_luminance(bg)
    lighter = max(l1, l2)
    darker = min(l1, l2)
    return (lighter + 0.05) / (darker + 0.05)


# Warm Ops final palette
# Canonical source: docs/design/ux-guidelines.md Section 1.1 + Section 5.1
# Also defined in: web/src/styles/design-tokens.css (--so-* prefix)
# Keep these dicts in sync with both files when colors change.

BACKGROUNDS = {
    "bg-base": "#0a0a12",
    "bg-surface": "#0f0f1a",
    "bg-card": "#13131f",
    "bg-card-hover": "#181828",
}

TEXT_COLORS = {
    "text-primary": "#e2e8f0",
    "text-secondary": "#94a3b8",
    "text-muted": "#8b95a5",
}

STATE_COLORS = {
    "accent": "#38bdf8",
    "accent-dim": "#0ea5e9",
    "success": "#10b981",
    "warning": "#f59e0b",
    "danger": "#ef4444",
}

# WCAG AA thresholds
NORMAL_TEXT_RATIO = 4.5  # normal text (< 18pt or < 14pt bold)
LARGE_TEXT_RATIO = 3.0  # large text (>= 18pt or >= 14pt bold)


def _print_contrast_row(
    fg_name: str,
    fg_hex: str,
    bg_name: str,
    bg_hex: str,
    failures: list[str],
) -> None:
    """Print a single contrast table row and record any failures."""
    ratio = contrast_ratio(fg_hex, bg_hex)
    normal_pass = ratio >= NORMAL_TEXT_RATIO
    large_pass = ratio >= LARGE_TEXT_RATIO
    normal_mark = "PASS" if normal_pass else "**FAIL**"
    large_mark = "PASS" if large_pass else "**FAIL**"
    print(
        f"| `{fg_name}` | `{fg_hex}` | `{bg_name}` | `{bg_hex}` "
        f"| {ratio:.2f}:1 | {normal_mark} | {large_mark} |"
    )
    if not normal_pass:
        failures.append(
            f"  {fg_name} ({fg_hex}) on {bg_name} ({bg_hex}): "
            f"{ratio:.2f}:1 (need {NORMAL_TEXT_RATIO}:1)"
        )


def _print_failures(failures: list[str]) -> None:
    """Print failure summary or success message."""
    if failures:
        print(f"## Failures ({len(failures)})")
        print()
        for f in failures:
            print(f"- {f}")
        print()
        print(
            "**Action**: Colors marked FAIL for normal text must only be "
            "used at large text sizes (>= 18pt / 24px, or >= 14pt / 18.67px "
            "bold), or the color must be adjusted."
        )
    else:
        print("**All combinations pass WCAG AA for normal text.**")


def main() -> None:
    """Print WCAG AA contrast verification table for the Warm Ops palette."""
    all_fg = {**TEXT_COLORS, **STATE_COLORS}

    print("# WCAG AA Contrast Verification -- Warm Ops Palette")
    print()
    print("Generated by `scripts/wcag_check.py`.")
    print()
    print("Thresholds: normal text >= 4.5:1, large text >= 3.0:1.")
    print()
    print(
        "| Foreground | Hex | Background | Hex | Ratio | "
        "Normal (4.5:1) | Large (3.0:1) |"
    )
    print(
        "|------------|-----|------------|-----|------:|"
        ":--------------:|:-------------:|"
    )

    failures: list[str] = []
    for fg_name, fg_hex in all_fg.items():
        for bg_name, bg_hex in BACKGROUNDS.items():
            _print_contrast_row(fg_name, fg_hex, bg_name, bg_hex, failures)

    print()
    _print_failures(failures)


if __name__ == "__main__":
    main()
