package compose

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

// Volatile image-reference patterns: Renovate rotates these on a weekly
// cadence (DHI digest pins) or whenever upstream cuts a new minor
// (busybox / postgres tags). Before this normalisation, every rotation
// required a human to run `UPDATE_GOLDEN=1 go -C cli test
// ./internal/compose/...` and push the regenerated bytes. The
// goldens are masked at compare time so the structural fidelity
// assertions still fire while the volatile fields stop tripping
// equality.
//
//   - any `@sha256:<64-hex>` digest (DHI postgres, DHI nats,
//     ghcr.io/aureliolo/* digest pins, busybox digest)
//   - `busybox:<tag>-musl`
//   - `pgvector:<pgvector-ver>-pg<pgN>-debianN` (the DHI postgres image
//     ships pgvector; the digest pattern already covers its digest)
//   - `nats:<tag>-(alpine|debianN)` (DefaultNATSImageTag uses the same
//     version-suffix pattern as postgres; tunnel-mode goldens that
//     render the NATS service would otherwise drift on Renovate's
//     weekly DHI rotation alongside postgres)
var (
	sha256DigestRE = regexp.MustCompile(`@sha256:[0-9a-f]{64}`)
	busyboxTagRE   = regexp.MustCompile(`busybox:[0-9.]+-musl`)
	postgresTagRE  = regexp.MustCompile(`pgvector:[0-9.]+-pg[0-9]+-(debian[0-9]+)`)
	natsTagRE      = regexp.MustCompile(`nats:[0-9.]+-(alpine|debian[0-9]+)`)
)

// normalize masks Renovate-rotated digest and version-suffixed tag
// fields so weekly bumps stop tripping the compose-template goldens.
// Applied to BOTH the rendered output and the on-disk golden inside
// compareGolden before equality compare; the byte-level structural
// assertions in each test continue to validate the rest.
func normalize(s string) string {
	s = sha256DigestRE.ReplaceAllString(s, "@sha256:<DIGEST>")
	s = busyboxTagRE.ReplaceAllString(s, "busybox:<TAG>-musl")
	s = postgresTagRE.ReplaceAllString(s, "pgvector:<TAG>-$1")
	s = natsTagRE.ReplaceAllString(s, "nats:<TAG>-$1")
	return s
}

func compareGolden(t *testing.T, name string, actual []byte) {
	t.Helper()
	golden := filepath.Join("..", "..", "testdata", name)

	// Normalise both sides so Renovate-rotated digests / tags do not
	// trip equality. UPDATE_GOLDEN=1 persists the NORMALISED actual
	// so committed goldens carry placeholders, not live values --
	// this keeps the golden bytes stable across digest rotations
	// while still letting contributors regenerate after a legitimate
	// structural change.
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.MkdirAll(filepath.Dir(golden), 0o755); err != nil {
			t.Fatalf("create testdata dir: %v", err)
		}
		if err := os.WriteFile(golden, []byte(normalize(string(actual))), 0o644); err != nil {
			t.Fatalf("update golden: %v", err)
		}
		return
	}

	expected, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("golden file %s missing: %v\nRun with UPDATE_GOLDEN=1 to create", golden, err)
	}

	if normalize(string(expected)) != normalize(string(actual)) {
		t.Errorf("output differs from golden file %s\nRun with UPDATE_GOLDEN=1 to update", name)
	}
}

// TestNormalizeMasksVolatileImageFields exercises the regex helper in
// isolation so a regex bug surfaces here, not as a confusing
// "golden differs" failure on an unrelated PR. The matrix covers all
// three volatile patterns plus a NEGATIVE assertion that
// structural fields (port maps, env vars, service names) survive
// untouched.
func TestNormalizeMasksVolatileImageFields(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name  string
		input string
		want  string
	}{
		{
			name:  "sha256_digest_masked",
			input: "image: ghcr.io/aureliolo/synthorg-backend@sha256:f36701e0a15a97186ccc59bbe9a6217b649edecb36ce32d07fa31bf5ad15e56d",
			want:  "image: ghcr.io/aureliolo/synthorg-backend@sha256:<DIGEST>",
		},
		{
			name:  "busybox_tag_masked",
			input: "image: busybox:1.38-musl",
			want:  "image: busybox:<TAG>-musl",
		},
		{
			name:  "busybox_tag_and_digest_both_masked",
			input: "image: busybox:1.38-musl@sha256:f36701e0a15a97186ccc59bbe9a6217b649edecb36ce32d07fa31bf5ad15e56d",
			want:  "image: busybox:<TAG>-musl@sha256:<DIGEST>",
		},
		{
			name:  "pgvector_debian_tag_masked",
			input: "image: dhi.io/pgvector:0.8-pg18-debian13",
			want:  "image: dhi.io/pgvector:<TAG>-debian13",
		},
		{
			name: "pgvector_tag_and_digest_both_masked",
			input: "image: dhi.io/pgvector:0.8-pg18-debian13@sha256:" +
				"374f7b2b39fd75d559013f44dd24781d187686c6ea708dc1c8f54c7fae05f958",
			want: "image: dhi.io/pgvector:<TAG>-debian13@sha256:<DIGEST>",
		},
		{
			name:  "nats_alpine_tag_masked",
			input: "image: dhi.io/nats:2.14-alpine",
			want:  "image: dhi.io/nats:<TAG>-alpine",
		},
		{
			name:  "nats_debian_tag_masked",
			input: "image: dhi.io/nats:2.14-debian13",
			want:  "image: dhi.io/nats:<TAG>-debian13",
		},
		{
			name:  "ports_and_env_untouched",
			input: `      - "3001:3001"` + "\n" + `      SYNTHORG_DB_PATH: "/data/synthorg.db"`,
			want:  `      - "3001:3001"` + "\n" + `      SYNTHORG_DB_PATH: "/data/synthorg.db"`,
		},
		{
			name:  "synthorg_image_tag_untouched",
			input: "image: ghcr.io/aureliolo/synthorg-backend:v0.7.2",
			want:  "image: ghcr.io/aureliolo/synthorg-backend:v0.7.2",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := normalize(tc.input)
			if got != tc.want {
				t.Errorf("normalize(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

// TestGoldensSurviveDigestRotation verifies the normalisation helper
// absorbs Renovate-rotated busybox tag and digest drift. Mutates the
// generated output's busybox image line to a fictional bump, then
// confirms the golden still matches via compareGolden.
//
// Without normalize() this assertion would fail every time Renovate
// merges a busybox or DHI digest bump; with it, only structural
// changes need a golden refresh. Failing this test signals that the
// regex coverage is too narrow OR the template's busybox image
// reference shape changed (in which case update the regex above and
// this test's setup expectation together).
func TestGoldensSurviveDigestRotation(t *testing.T) {
	// Skip parallel scheduling under UPDATE_GOLDEN=1 because compareGolden
	// then calls os.WriteFile on cli/testdata/compose_default.yml, the
	// same file TestGenerateDefault writes; concurrent non-atomic
	// WriteFile calls can interleave truncate + write between the two
	// goroutines. Under the default read-only mode (no env var) the
	// parallel scheduling is safe and we keep it.
	if os.Getenv("UPDATE_GOLDEN") != "1" {
		t.Parallel()
	}
	p := Params{
		CLIVersion:         "dev",
		ImageTag:           "latest",
		BackendPort:        3001,
		WebPort:            3000,
		LogLevel:           "info",
		PersistenceBackend: "sqlite",
		MemoryBackend:      "sqlvector",
		BusBackend:         "internal",
	}
	out, err := Generate(p)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// Confirm the production busybox image line is present before
	// mutation -- a missing line silently turns the rotation test
	// into a no-op golden compare.
	if !busyboxTagRE.Match(out) {
		t.Fatal("test setup: rendered output has no `busybox:<tag>-musl` line; template change?")
	}
	if !sha256DigestRE.Match(out) {
		t.Fatal("test setup: rendered output has no `@sha256:<digest>` line; template change?")
	}

	bumped := busyboxTagRE.ReplaceAll(out, []byte("busybox:99.99-musl"))
	bumped = sha256DigestRE.ReplaceAll(bumped,
		[]byte("@sha256:0000000000000000000000000000000000000000000000000000000000000000"),
	)
	if bytes.Equal(out, bumped) {
		t.Fatal("test setup: bump mutation produced an identical byte sequence")
	}

	compareGolden(t, "compose_default.yml", bumped)
}
