"""Unified provider interface for LLM completion.

Exports protocols, base classes, domain models, enums, errors,
driver implementations, and the provider registry.
"""

from .base import BaseCompletionProvider
from .capabilities import ModelCapabilities
from .cassette import (
    CASSETTE_FORMAT_VERSION,
    CassetteCompletionProvider,
    CassetteConfig,
    CassetteError,
    CassetteFormatError,
    CassetteMode,
    CassetteRedactor,
    CassetteReplayExhaustedError,
    CassetteReplayMissError,
    CassetteSession,
    NullRedactor,
    PatternRedactor,
)
from .cost_recording import (
    CostRecordingContext,
    cost_recording_scope,
    current_cost_context,
    resolve_currency,
)
from .drivers import LiteLLMDriver
from .enums import MessageRole, StreamEventType
from .errors import (
    AuthenticationError,
    ContentFilterError,
    DriverAlreadyRegisteredError,
    DriverFactoryNotFoundError,
    DriverNotRegisteredError,
    InvalidRequestError,
    ModelNotFoundError,
    ProviderConnectionError,
    ProviderError,
    ProviderInternalError,
    ProviderTimeoutError,
    RateLimitError,
)
from .models import (
    ZERO_TOKEN_USAGE,
    ChatMessage,
    CompletionConfig,
    CompletionResponse,
    StreamChunk,
    TokenUsage,
    ToolCall,
    ToolDefinition,
    ToolResult,
    add_token_usage,
)
from .protocol import CompletionProvider
from .registry import ProviderRegistry
from .resilience import (
    RateLimiter,
    RetryExhaustedError,
    RetryHandler,
)
from .routing import (
    STRATEGY_MAP,
    STRATEGY_NAME_COST_AWARE,
    STRATEGY_NAME_FASTEST,
    STRATEGY_NAME_MANUAL,
    STRATEGY_NAME_ROLE_BASED,
    STRATEGY_NAME_SMART,
    CostAwareStrategy,
    FastestStrategy,
    ManualStrategy,
    ModelResolutionError,
    ModelResolver,
    ModelRouter,
    NoAvailableModelError,
    ResolvedModel,
    RoleBasedStrategy,
    RoutingDecision,
    RoutingError,
    RoutingRequest,
    RoutingStrategy,
    SmartStrategy,
    UnknownRoutingStrategyError,
)

__all__ = [
    "CASSETTE_FORMAT_VERSION",
    "STRATEGY_MAP",
    "STRATEGY_NAME_COST_AWARE",
    "STRATEGY_NAME_FASTEST",
    "STRATEGY_NAME_MANUAL",
    "STRATEGY_NAME_ROLE_BASED",
    "STRATEGY_NAME_SMART",
    "ZERO_TOKEN_USAGE",
    "AuthenticationError",
    "BaseCompletionProvider",
    "CassetteCompletionProvider",
    "CassetteConfig",
    "CassetteError",
    "CassetteFormatError",
    "CassetteMode",
    "CassetteRedactor",
    "CassetteReplayExhaustedError",
    "CassetteReplayMissError",
    "CassetteSession",
    "ChatMessage",
    "CompletionConfig",
    "CompletionProvider",
    "CompletionResponse",
    "ContentFilterError",
    "CostAwareStrategy",
    "CostRecordingContext",
    "DriverAlreadyRegisteredError",
    "DriverFactoryNotFoundError",
    "DriverNotRegisteredError",
    "FastestStrategy",
    "InvalidRequestError",
    "LiteLLMDriver",
    "ManualStrategy",
    "MessageRole",
    "ModelCapabilities",
    "ModelNotFoundError",
    "ModelResolutionError",
    "ModelResolver",
    "ModelRouter",
    "NoAvailableModelError",
    "NullRedactor",
    "PatternRedactor",
    "ProviderConnectionError",
    "ProviderError",
    "ProviderInternalError",
    "ProviderRegistry",
    "ProviderTimeoutError",
    "RateLimitError",
    "RateLimiter",
    "ResolvedModel",
    "RetryExhaustedError",
    "RetryHandler",
    "RoleBasedStrategy",
    "RoutingDecision",
    "RoutingError",
    "RoutingRequest",
    "RoutingStrategy",
    "SmartStrategy",
    "StreamChunk",
    "StreamEventType",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "ToolResult",
    "UnknownRoutingStrategyError",
    "add_token_usage",
    "cost_recording_scope",
    "current_cost_context",
    "resolve_currency",
]
