"""API event constants."""

from typing import Final

API_REQUEST_STARTED: Final[str] = "api.request.started"
API_REQUEST_COMPLETED: Final[str] = "api.request.completed"
API_REQUEST_ERROR: Final[str] = "api.request.error"
API_HEALTH_CHECK: Final[str] = "api.health.check"
API_APP_STARTUP: Final[str] = "api.app.startup"
API_APP_SHUTDOWN: Final[str] = "api.app.shutdown"
API_WS_CONNECTED: Final[str] = "api.ws.connected"
API_WS_DISCONNECTED: Final[str] = "api.ws.disconnected"
API_GUARD_DENIED: Final[str] = "api.guard.denied"
API_BUS_BRIDGE_SUBSCRIBE_FAILED: Final[str] = "api.bus_bridge.subscribe.failed"
API_BUS_BRIDGE_POLL_ERROR: Final[str] = "api.bus_bridge.poll.error"
API_WS_INVALID_MESSAGE: Final[str] = "api.ws.invalid_message"
API_WS_SUBSCRIBE: Final[str] = "api.ws.subscribe"
API_WS_UNSUBSCRIBE: Final[str] = "api.ws.unsubscribe"
API_WS_UNKNOWN_ACTION: Final[str] = "api.ws.unknown_action"
API_RESOURCE_NOT_FOUND: Final[str] = "api.resource.not_found"
API_TASK_UPDATED: Final[str] = "api.task.updated"
API_TASK_DELETED: Final[str] = "api.task.deleted"
